resources:
      
  - name: gitresource
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: vijayreddy1991/test
      files:  # optional
        include: n.*
        exclude: r.* 
      buildOn:  # optional
        commit: true
#          pullRequestCreate: true
#          pullRequestClose: true
#          releaseCreate: true
        tagCreate: true
      shallowDepth: 1  # optional 
      
  - name: gitresource1
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: vijayreddy1991/test
      branches:  # optional
        include: m.*
        exclude: r.*     
      buildOn:  # optional
        commit: true
#          pullRequestCreate: true
#          pullRequestClose: true
#          releaseCreate: true
        tagCreate: true
      shallowDepth: 1  # optional     
      
  - name: gitresource2
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: vijayreddy1991/test
      files:  # optional
        include: n.*
        exclude: r.*
      branches:  # optional
        include: m.*
        exclude: r.*     
      buildOn:  # optional
        commit: true
#          pullRequestCreate: true
#          pullRequestClose: true
#          releaseCreate: true
        tagCreate: true
      shallowDepth: 1  # optional       
      
pipelines:

  - name: pipelines_files
  
    steps:
      - name: s_BashTriggerfiles
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitresource
        execution:
          onExecute:
            - printenv 
            - pushd $res_gitresource_resourcePath
            - git log
            - ls    
            
            
  - name: pipelines_branch
  
    steps:
      - name: s_BashTriggerbranch
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitresource1
        execution:
          onExecute:
            - printenv 
            - pushd $res_gitresource_resourcePath
            - git log
            - ls
            
            
  - name: pipelines_both
  
    steps:
      - name: s_BashTriggerboth
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitresource2
        execution:
          onExecute:
            - printenv 
            - pushd $res_gitresource_resourcePath
            - git log
            - ls
          
